### ISSUE TITLE
Concourse stuck on checking new version

### ISSUE THREAD

**Issue by danlsgiga** [cludden/concourse-keyval-resource#3]
When using this resource without an initial `put`, Concourse gets stuck on checking the latest version of the resource.

This happens even when setting `check_every: never` and defining the `initial_mapping`, which is the recommended approach for when you don't have an initial `put` step before a `get`, according to the docs

![image](https://user-images.githubusercontent.com/1944846/194644181-dbe64fac-891d-43de-ae3c-542b19738177.png)

**Comment by danlsgiga** [comment]
It seem to work if you only specify `initial_mapping`. It doesn't work if `check_every: never` is defined.

**Comment by cludden** [comment]
I think there might be some confusion here, the docs state:
> `initial_mapping` | `string` | a Bloblang mapping that can be used to customize the initial version returned by this resource, **if not specified**, checking is a noop and should be disabled via `check_every: never`

I agree that the current punctuation could make that easy to misinterpret, but I believe the resource is functioning as expected. In most cases, it's intended to be used as a `put` only resource, in which case, an `initial_mapping` configuration *is not* required, and `check_every: never` is encouraged. Certain use cases might require a `get` prior to a `put` (e.g. for importing data from a previous build of the same job), in which case, an `initial_mapping` configuration *is* required, and `check_every` should be set to something other than `never`, to prevent the situation you've alluded to in your issue.
